services:
  - type: web
    name: dnet-orchestrator
    env: docker
    dockerfilePath: orchestrator-dotnet/Dockerfile
    autoDeploy: true
    plan: starter
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: CONNECTION_STRING
        sync: false

  - type: web
    name: dnet-python
    env: docker
    dockerfilePath: worker-python/Dockerfile
    autoDeploy: true
    plan: starter
    envVars:
      - key: NEWSAPI_KEY
        sync: false
      - key: BUILTWITH_API_KEY
        sync: false
      - key: BUILTWITH_FORCE_MOCK
        value: "true"    # anahtarlar yoksa mock devrede kalsın
