services:
  - type: web
    name: dnet-orchestrator
    env: docker
    dockerfilePath: orchestrator-dotnet/Dockerfile
    autoDeploy: true
    plan: starter
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      # Bağlantı/sırlar için sync:false kullan; panelden girersin:
      - key: CONNECTION_STRING
        sync: false
      # gRPC kullanıyorsan health check belirtmek istemeyebilirsin;
      # REST health endpoint'in varsa aç:
    # healthCheckPath: /health

  - type: worker
    name: dnet-worker
    env: docker
    dockerfilePath: worker-python/Dockerfile
    autoDeploy: true
    plan: starter
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: SOME_API_KEY
        sync: false
